# Generated by Django 5.1.2 on 2024-10-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_cards_card_rename_factions_faction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_type',
            options={'ordering': ['type_name'], 'verbose_name_plural': 'Type'},
        ),
        migrations.AlterModelOptions(
            name='faction',
            options={'ordering': ['faction_name'], 'verbose_name_plural': 'Faction'},
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(upload_to='media/card_images/'),
        ),
    ]
