# Generated by Django 5.1.2 on 2024-10-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_type_options_alter_faction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(upload_to='card_images/'),
        ),
    ]
