# Generated by Django 5.1.2 on 2024-10-14 13:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
