# Generated by Django 5.1.2 on 2024-10-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_card_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_defense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
